---
en:
  languageName: "English"
  contentDir: 'content/en'
  weight: 100
  taxonomies:
    category: categories
    tag: tags
    series: series
  menu:
    main:
      - name: Blog
        url: blog/
        weight: 5
      - name: Projects
        url: projects/
        weight: 10
      - name: Art
        url: https://www.artstation.com/jcs090218
        weight: 15
      - name: Resume
        url: storage/Resume.pdf
        weight: 20
      - name: Search
        url: search/
        weight: 25

zh-TW:
  languageName: "繁體中文"
  contentDir: 'content/zh-TW'
  weight: 90
  taxonomies:
    category: categories
    tag: tags
    series: series
  menu:
    main:
      - name: 部落格
        url: blog/
        weight: 5
      - name: 專案
        url: projects/
        weight: 10
      - name: 藝術
        url: https://www.artstation.com/jcs090218
        weight: 15
      - name: 履歷
        url: ../storage/Resume.pdf
        weight: 20
      - name: 搜尋
        url: search/
        weight: 25
