name: Update Submodules

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Submodule update
      run: |
        git submodule init
        git submodule update --remote --merge

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Update submodules'
        body: ''
        commit-message: 'Update all submodules'
        branch: submodules-update
        delete-branch: true
